#!/bin/bash

echo "Creating rc for uniclient"

INIT_PATH=/etc/init.d/uniclient.init;
DIR=/var/run/uniclient
GRP=uniclient
USR=uniclient

#checking if file exists
if [ ! -f "$INIT_PAPTH" ];
then
touch $INIT_PATH;
fi

#writing rc to file
echo "#!/bin/bash" > $INIT_PATH;

echo "mkdir $DIR;" >> $INIT_PATH;

echo "chgrp $GRP $DIR;" >> $INIT_PATH;

echo "chmod 770 $DIR" >> $INIT_PATH;

#making rc executable
chmod +x $INIT_PATH;

MY_PATH="`dirname \"$0\"`"              # relative
MY_PATH="`( cd \"$MY_PATH\" && pwd )`"  # absolutized and normalized
if [ -z "$MY_PATH" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  exit 1  # fail
fi

#running group script to make sure group exists
$MY_PATH/a0-user-group;

if ! [ -d "$DIR" ];then
	#creating directories for use before restart
	mkdir -p $DIR;
	chgrp $GRP $DIR;
	chmod 770 $DIR;
fi


#creating rc link to rc3 to make sure it runs as root
RC_LINK=/etc/rc3.d/S02uniclient.init;

if ! [ -L "$RC_LINK" ];
then
ln -s $INIT_PATH $RC_LINK;
fi

#this is needed for ubuntu
uname -v | awk '!/Ubuntu/{exit 1}' && sudo update-rc.d uniclient.init defaults;

echo "ALL DONE!";
